# Generated by Django 4.2.18 on 2025-01-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('data_admissao', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
